---
# tasks file for vijayapache

- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Start Apache
  service:
    name: httpd
    state: started

- name: Configure index page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0777'
